/****************************************************************************\
 ***
 *** File                  : dsaApplProcSyncFcn.h
 ***
 *** Generated by dSPACE Tools.
 *** (c) Copyright 2012, dSPACE GmbH. All rights reserved.
\****************************************************************************/

#if !defined(UF_APPLICATION_PROCESS_SYNC_H_)
#  define    UF_APPLICATION_PROCESS_SYNC_H_

#  include <IOCode_Data.h>

void ucf_dsaApplProcSyncFcn_Create(DsTErrorList ErrorList, ucf_Application_Process_SyncStruct_T * pBlockInstance);
void ucf_dsaApplProcSyncFcn_Init(DsTErrorList ErrorList, ucf_Application_Process_SyncStruct_T * pBlockInstance);
void ucf_dsaApplProcSyncFcn_Stop(DsTErrorList ErrorList, ucf_Application_Process_SyncStruct_T * pBlockInstance);
void ucf_dsaApplProcSyncFcn_Unload(DsTErrorList ErrorList, ucf_Application_Process_SyncStruct_T * pBlockInstance);
void ucf_dsaApplProcSyncFcn_Terminate(DsTErrorList ErrorList, ucf_Application_Process_SyncStruct_T * pBlockInstance);
void ucf_dsaApplProcSyncFcnTrigger(ucf_Application_Process_SyncStruct_T * pBlockInstance, UInt32 * pValue);
#endif
